[workspace]
members = [
    "crates/*",
]
default-members = [
    "crates/moss"
]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
bitflags = "2.4.1"
bytes = "1.5.0"
chrono = "0.4.30"
clap = { version = "4.4.14", features = ["derive", "string"] }
crossterm = "0.27.0"
dialoguer = "0.11.0"
dirs = "5.0"
indicatif = "0.17.7"
itertools = "0.12.0"
futures = "0.3.30"
hex = "0.4.3"
log = "0.4"
nom = "7.1.3"
nix = { version = "0.27.1", features = ["user", "fs", "sched", "process", "mount", "hostname", "signal", "term"] }
once_cell = "1.19.0"
petgraph = "0.6.4"
rayon = "1.8"
reqwest = { version = "0.11.23", default-features = false, features = ["rustls-tls", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
sha2 = "0.10.8"
sqlx = { version = "0.7.3", features = ["sqlite", "chrono", "runtime-tokio"] }
strum = { version = "0.25", features = ["derive"] }
thiserror = "1"
tokio = { version = "1.35", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["time"] }
tokio-util = { version = "0.7.9", features = ["io"] }
url = { version = "2.5.0", features = ["serde"] }
xxhash-rust = { version = "0.8.8", features = ["xxh3"] }
zstd = "0.12.4"

[profile.release]
lto = 'thin'

[profile.packaging]
inherits = "release"
lto = true
codegen-units = 1
opt-level = 3
# allow packaging system to do it
strip = "none"
debug = true

